//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA_has_PRODUCTO
    {
        public int RESERVA_ID_RESERVA { get; set; }
        public int PRODUCTO_ID_PRODUCTO { get; set; }
        public int CANTIDAD_PRODUCTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
